ui:
  default_width: 450
inputs_def:
  - handle: ndjsonPath
    description: "%path-to-the-input-ndjson-file2%"
    json_schema:
      type: string
      ui:widget: file
      ui:options:
        filters:
          - name: Newline Delimited JSON
            extensions:
              - ndjson
  - handle: sheetName
    description: "%name-of-the-excel-sheet%"
    json_schema:
      type: string
    value: Sheet1
  - handle: saveAs
    description: "%output-file-path-for-the-excel-file%"
    json_schema:
      type: string
      ui:widget: save
      ui:options:
        excludeAll: true
        filters:
          - name: Excel Workbook
            extensions:
              - xlsx
    value: null
    nullable: true
outputs_def:
  - handle: output
    description: "%path-to-the-generated-excel-file%"
    json_schema:
      type: string
      ui:widget: file
executor:
  name: nodejs
  options:
    entry: main.ts
    spawn: false
icon: ":carbon:table-split:"
title: "%ndjson-to-excel%"
description: "%converts-an-ndjson-newline-delimited-json-file-to-an-excel-sprea%"
