ui:
  default_width: 450
inputs_def:
  - handle: ndjsonPath
    description: "%path-to-the-input-ndjson-file%"
    json_schema:
      type: string
      ui:widget: file
      ui:options:
        filters:
          - name: Newline Delimited JSON
            extensions:
              - ndjson
  - handle: saveAs
    description: "%output-file-path-for-the-csv-file%"
    json_schema:
      type: string
      ui:widget: save
      ui:options:
        excludeAll: true
        filters:
          - name: CSV File
            extensions:
              - csv
    value:
    nullable: true
  - group: Optional
    collapsed: false
  - handle: delimiter
    description: "%csv-field-delimiter%"
    json_schema:
      type: string
    value:
    nullable: true
  - handle: includeHeaders
    description: "%include-column-headers-in-the-csv-file%"
    json_schema:
      type: boolean
    value: true
    nullable: true
outputs_def:
  - handle: output
    description: "%path-to-the-generated-csv-file%"
    json_schema:
      type: string
      ui:widget: file
executor:
  name: nodejs
  options:
    entry: main.ts
    spawn: false
icon: ":carbon:document-export:"
title: "%ndjson-to-csv%"
description: "%converts-an-ndjson-newline-delimited-json-file-to-a-csv-comma-se%"
